### Transform code into idiomatic Python
- Replace tradition index manupulation with python core looping idiomatic

In [1]:
# looping over a range of numbers
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [2]:
# idiomatic programming
for i in  range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### looping over a collection

In [3]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [4]:
for color in colors:
    print(color,end=" ")
    

red green yellow purple 

## looping backwards

In [5]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [6]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

### Looping in sorted list

In [7]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

###
- if x<=yandy<=z:
- if x<=y<=z:
- if x==True:
- if x:

### Pandas

In [8]:
import pandas as pd

In [10]:
dt ={'Id':[11,12,13,14,15],
    'firstname':['A','B','C','D','E'],
    'company':['aa','bb','cc','dd','ee'],
    'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt=pd.DataFrame(dt)

In [11]:
print(mydt)

   Id firstname company address
0  11         A      aa     Hyd
1  12         B      bb     Hyd
2  13         C      cc     Hyd
3  14         D      dd     Hyd
4  15         E      ee     Hyd


In [17]:
import os 
os.getcwd()

'C:\\Users\\exam'

In [25]:
os.chdir("C:\\users\\exam")# save to certain location 

In [32]:
mydt.to_csv('workingfile.csv',index=False)

In [35]:
pwd

'C:\\users\\exam'

### Reading the  data from CSV file

In [33]:
mydata=pd.read_csv('workingfile.csv')

In [34]:
print(mydata)

   Id firstname company address
0  11         A      aa     Hyd
1  12         B      bb     Hyd
2  13         C      cc     Hyd
3  14         D      dd     Hyd
4  15         E      ee     Hyd


In [37]:
mydata1=pd.read_csv('workingfile.csv',skiprows=1,
                  names=["custid","name","company","address"])

In [38]:
print(mydata1)

   custid name company address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


In [39]:
mydata1=pd.read_csv('workingfile.csv',skiprows=[1,2,3],
                  names=["custid","name","company","address"])

In [40]:
print(mydata1)

  custid       name  company  address
0     Id  firstname  company  address
1     14          D       dd      Hyd
2     15          E       ee      Hyd


### print only two columns
### print the large value from custid column
### print the least value from custid column
### average of custid column -- sum(li)/len(li)

### Numpy - Working with multi dimensions array
- numpy arrays is a bit.like pythonlist
- numpy array is data structure of numpy lib
- it's a shortcut for numeric python or numerical python

In [46]:
import numpy as np # import the numpy package

In [47]:
li=[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [50]:
array= np.array(li)
print(array)   # convert the list into array using np.array()

[1 2 3 4 5]


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [55]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [65]:
#  3 question 
# read  a number -- 19528
# print the large digit print the number
def printlarge(n):
    large=0
    while n!=0:
        r=n%10
        if large<r:
            large=r
        n=n//10  
    return large
printlarge(19528)

9

In [64]:
# TO PRINT PALINDROME COUNT BETWEEN TWO NUMBERS
def ispalindrome(n):
    rev=0
    buffer=n
    while n!=0:
        r=n%10
        rev=rev*10+r
        n=n//10
    if rev==buffer:
        return True
    else:
        return False
    return
def countpalindrome(lb,ub):
    cnt=0
    while lb!=ub:
        if ispalindrome(lb)==True:
            cnt=cnt+1
        lb=lb+1
    return cnt
countpalindrome(1,10)
countpalindrome(11,100)

9